server:
  port: 9092
management:  endpoints:    web:      exposure:        include: "*"
  endpoint:    health:      show-details: always
  health:    circuitbreakers:      enabled: true
resilience4j:  circuitbreaker:    instances:      fetchDefaultService: 
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 6
        ring-buffer-size-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50s
        record-exceptions:          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException
       