server:
  port: 8888


#spring:#  cloud:#    config:#      server:#        native:#          search-locations: file:///D://Labs//cloud-config

spring:  cloud:    config:      server:        git:          uri: https://github.com/Kishor-C/spring-cloud-ideas-config.git
          search-locations: foldername1, foldername2      
          
          
          