server:
  port: 8888


spring:  cloud:    config:      server:        git:          uri: https://github.com/Kishor-C/spring-cloud-ideas-config.git
          
        
          
          